### ISSUE TITLE
Crowdsourcing the training with a Zotero add-on

### ISSUE THREAD

**Issue by retrography** [inukshuk/anystyle-parser#50]
I have made a [proof-of-concept Zotero add-on](https://github.com/retrography/stylio) that works as a front-end for AnyStyle.io. It allows the user to import a formatted bibliography from the clipboard into Zotero's library. 

It truly feels magical. Try it for yourself. You just grab the bibliography from the end of an article, you select the menu item in Zotero... And boom... You have all the items in a nicely structured manner in your library!

I see many people using it if available as a public add-on. And if there is a easy-to-use interface in the plugin, similar to the website, that allows the users to make corrections to the results, I am sure the engine will become the best-trained one in the domain pretty soon. One can even see this implemented as a last recourse in Zotero's default _Import from Clipboard_ functionality (when the translators fail to detect any structured data in the text being pasted). 

But here are my questions: 
1. Are there any plans for providing such widespread services on the current servers? How many concurrent sessions can the server(s) take right now (I don't know how fast the current code is)? Are we even supposed to ramp up the adoption like that?
2. Given that API keys are really for the programmers and not the end users, how can we give the end users access to AnyStyle.io? Apart from the 100-lines limitation, do the current API keys bear any other limitation?

**Comment by inukshuk** [comment]
That's pretty cool. I've been planning to add an 'import to Zotero' button there for a long time.

Having said that, the 'current servers' is really just a tiny xen image with approximately 200 MB of memory. We're currently using Puma with multiple threads for parsing and Redis-backed workers for training. The larger the model gets, training takes a long time and a lot of memory so, I'm sure it can be done, but at the moment the service is just provided 'as is' because at its current setup it wouldn't scale very far.

cc @dstillman

**Comment by retrography** [comment]
But is there a way I can use my API key in the add-on's distribution? If I put the API key in the add-on's package, it will be synonymous with revealing it publicly, so it can't really be done... I can as well add a configuration page so that he users add their own API keys or even send an API key request... Is that an acceptable solution for you?

**Comment by inukshuk** [comment]
Both options are absolutely fine; the important thing is that each user should have their own key.  It's OK if you send the key request for them (note that there can be only one key per e-mail address). This way, it is easier for us to tell if someone uses the API excessively -- I just run the server on the side, with very limited resources as noted above, and I'd like it to be available to everyone so I added the API keys in order to be able to contact or block individual key owners if necessary.
