### ISSUE TITLE
Getting a 404 error with JSON API

### ISSUE THREAD

**Issue by cpikas** [inukshuk/anystyle-parser#54]

**Comment by inukshuk** [comment]
Sorry, I was out of town for awhile. Can you post the full request for which you're seeing the 404 (not including your API key)?

**Comment by cpikas** [comment]
There might be other problems with this script:
`library("jsonlite", lib.loc="~/R/win-library/3.3")
library("httr", lib.loc="~/R/win-library/3.3")

key<- "--"

string<-"Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)"

req<- POST("http://anystyle.io/parse/references",
                 add_headers("Content-Type" = "application/json;charset=UTF-8"),
                 body = '"format":"bib","access_token": "key", "references": ["Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)" ] } '
        )

`
There may be issues with that code  - but even going directly to https://anystyle.io/parse/references yields a 404

**Comment by inukshuk** [comment]
You can connect to the API only via SSL (so the URL in the script above will not work); visiting https://anystyle.io/parse/references will give you a 404 because you need to accept json and set the format parameter. The body must be valid JSON (in your example, the opening brace is missing). Finally, the format parameter should be part of the URL (not set in the body).

That is to say, try connecting to `https://anystyle.io/parse/references.bib` with `Content-Type: application/json;charset=utf-8` and a body like

```{
  "access_token": "BADC0DE000BADC0DE000BADC0DE",
  "references": [
    "Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)"
  ]
}
```
With a valid access token.
