### ISSUE TITLE
Parsing multiple citation references within single line

### ISSUE THREAD

**Issue by FlavourDaveMasterDDissle-theDtotheissle** [inukshuk/anystyle-parser#55]
Thank you for the great work!

In your online-demo the tool automatically splits a single line of multiple citations correctly into multiple lines and parses them afterwards.

Can you help me how to do that in irb?

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
E.g.: upload this gist https://gist.github.com/FlavourDaveMasterDDissle-theDtotheissle/da1acba2d32b97879a551819f59fdc30

**Comment by inukshuk** [comment]
Hmm, no, unfortunately that's not the case: the parser expects one reference per line (the online version requires one reference per line too). Extracting references from a larger corpus is a separate, albeit related, problem which anystyle-parser does not tackle currently since I've only ever needed to parse bibliographies where it is usually relatively easy to extract references on a line by line basis (though long references which span multiple lines in older pdfs are often problematic).
