### ISSUE TITLE
Text gets truncated while exporting it to "CiteProc/JSON"

### ISSUE THREAD

**Issue by ckannaiah** [inukshuk/anystyle-parser#64]
Hi,

Here is the reference:

New York State Department of Education. (2011). Graduate level clinically rich teacher preparation pilot program: 2011-2016. Retrieved from http://www.p12.nysed.gov/ compcontracts/rttt/teacherprep

Here is the online output:

![image](https://user-images.githubusercontent.com/30225139/28315280-6d9f17a6-6bdb-11e7-9fc8-ee5cadac7c3a.png)

Here is the CiteProc/JSON output:

[{"title":"Graduate level clinically rich teacher preparation pilot program","URL":"http://www.p12.nysed.gov/","language":"en","urldate":"2011-2016. from","publisher":"New York State Department of Education","issued":{"date-parts":[[2011]]},"id":"unknown2011a","type":"report"}]

In the input, there is a space in the URL. If you see the online output, it's being captured correctly with space. However, if we export the output, then the text after the space (compcontract/rttt/ ...) is truncated.

Can you look in to this?

**Comment by inukshuk** [comment]
I suppose the normalizer could join all URLs (if there is more than one) with a space (I guess a space would be most neutral). This wouldn't fix the URL of course but would preserve the input in your particular case. There's no silver bullet to fix the URL though, because multiple URLs could occur at various places in a reference (in theory) so we couldn't assume that it's all a single URL.

Aside: in the example above you should label '2011-2016.' as part of the title, and the rest as 'Acessed' -- at least this is more common to how the default label is trained (with the public model there is not really any quality control / consistency though!).

**Comment by ckannaiah** [comment]
I understand that the public model will not 100% correct. However, is there anyway that the text which gets truncated can be avoided.

**Comment by inukshuk** [comment]
Yes, XML output skips the normalizer so your input will be preserved.

CiteProc JSON uses the normalizer (which parses names and normalizes a lot of other fields) and only expects a single URL (that's why subsequent URLs are being dropped). I'm not convinced that joining multiple URLs is the best approach in general.

If you have a lot of links with spaces I would either use XML output (or use the library locally, because there are more format options and you can adjust normalizers) or fix the URLs before you parse them.
