### ISSUE TITLE
Data loss in XML output

### ISSUE THREAD

**Issue by vijaynaidu** [inukshuk/anystyle-parser#65]
Hi @inukshuk  AnyStyle does the fantastic job in segmenting and identifying labels. But fear of data loss, can you help me on how could we preserve all the data input given to AnyStyle parsing. Spaces are lost in the xml output (i prefer only xml output), i understood that we split based on spaces as it in _parser.rb_  _tokenize()_ 

How could we preserve spaces. Also is there any probability of losing data other than spaces during formation of other properties like author, title, volume..e.t.c

Eg. 
`[1] J. C. Slonczewski and P. R. Weiss, "Band structure of graphite," Phys. Rev., vol. 109, p. 272, 1958.`

**Expected Output:**
`<?xml version="1.0" encoding="UTF-8"?><references><reference><label>[1] </label><author>J. C. Slonczewski and P. R. Weiss, </author><title>"Band structure of graphite," </title><journal>Phys. Rev., </journal><volume>vol. 109, </volume><pages>p. 272, </pages><date>1958.</date></reference></references>`

**NOTE!!: Spaces are lost in expected output Eg. [1]{space_here} `<label>[1] </label>`** 

**Output from AnyStyle:**
`<?xml version="1.0" encoding="UTF-8"?><references><reference><label>[1]</label><author>J. C. Slonczewski and P. R. Weiss,</author><title>"Band structure of graphite,"</title><journal>Phys. Rev.,</journal><volume>vol. 109,</volume><pages>p. 272,</pages><date>1958.</date></reference></references>`

Thanks

**Comment by inukshuk** [comment]
First off, just a quick note about the [available formats](https://github.com/inukshuk/anystyle-parser/blob/master/lib/anystyle/parser/parser.rb#L6) and their differences regarding the three phases of the parser:

1. Labelling: each token is assigned a label (e.g., author, date, etc.) (heuristic)
2. Segmentation: consecutive tokens with the same label are grouped together (deterministic)
3. Normalization: each group is normalized individually (e.g., names, dates, or edition numbers are parsed) (deterministic)

Some formats skip normalization (or even segmentation) and some don't. If you're concerned about data loss, you should always pick a format which skips normalization, because that's the only case (with the exception of white space!) where data loss happens: obviously, if you parse the edition number '6' from a string like '6th ed.' or the page range '2-4' from 'pp. 2-4' you're losing parts of the original string. This is the desired behaviour in most cases, because typically the information lost there is style dependent (the idea is that you then post-process something like the CiteProc JSON output with a CSL style).

So that leaves you with the XML, tags, raw, and hash formats (tags is basically just a simplified XML output which we use for training data internally): all these formats skip normalization so there should be no data loss there with the exception of white space. Like you say, we tokenize based on white space, so you will always lose white space between tokens (like your example above, but note that you would also lose multiple spaces inside a segment, not only between them). The reason for this is that there are many features which depend on the position of characters; in other words, the feature analysis of `[1] `  [1]` and `[1]` would not be the same and lead to inferior results. It is also arguable where the extra pace belongs to: for instance, in your example, why should the space between volume and pages be labelled as volume and not as pages?

Having said all that, here is what you can do: use the raw output format which returns each token with the corresponding label and tokenize your input (preserving white space) separately: then, all you need to do is replace every token of the raw output with your own token (leaving the labels untouched).

**Comment by vijaynaidu** [comment]
@inukshuk :+1: Thanks again for your help. You got my point and helped to solve my confusion. Nice to listen phases from you, easy to understand AnyStyle :). Yes, agreed with you, spaces are arguable but i considered comma followed by space in this case. Sure, would extend AnyStyle using "raw format"  for doing this, Thanks
