### ISSUE TITLE
Getting the entire set of labels (along with the sub-labels) used in the model

### ISSUE THREAD

**Issue by Pryanga** [inukshuk/anystyle-parser#90]
Dear Mr. @inukshuk 

I am analyzing Anystyle parser and I would like to know the labels used in the model.
With Anystyle.parser.model.labels the output is:
`["accessed", "author", "authority", "booktitle", "date", "director", "doi", "edition", "editor", "event", "genre", "isbn", "journal", "location", "medium", "note", "pages", "producer", "publisher", "section", "source", "title", "translator", "unknown", "url", "volume"]`

However, when I set the format = :citeproc, there are more labels than the ones specified above.
`irb(main):033:0> Myprs.parse("Lombard, M.-A. 1989. “Tchador à l’école: deux mois d’un débat qui divise la France.” Le Figaro, 27 November, p. 10.", format = :citeproc) => [{"author"=>[{"family"=>"Lombard", "given"=>"M.-A."}], "title"=>"Tchador à l’école: deux mois d’un débat qui divise la France.", "container-title"=>"Le Figaro", "volume"=>"27", "page"=>"10", "language"=>"", "id"=>"lombard1989a", "issued"=>{"date-parts"=>[[1989, 11]]}, "type"=>"article-journal"}]`
Is there a way that I can view/extract all the labels (along with its sub-labels) used in the model?

Your help will aid me in my school project.

**Comment by inukshuk** [comment]
With the caveat that the parser is currently undergoing many changes and much of the following will not apply any more to future versions, here's a quick answer that should help clarify things:

The `citeproc` output follows conventions used by the CSL/JSON format. There is some conversion going on, so the labels do not reflect the ones used by the parser anymore. I would suggest you use the `normalized`, `xml`, `hash` or `raw` outputs, because they are more closely aligned to the parser.

What labels are there? That depends on your training data. But basically, you're on the right track: `Anystyle.parser.model.labels` will give you all the labels the current model knows about; if you use `xml` or `raw` output, you will never see anything else. `normalized` may add `type` and `language` and manipulate some of the other labels.

All the best for your project!
